version: '3.6'

networks:
  net:
    driver: overlay
    attachable: true

services:
  zabbix-server:
    build:
      context: ./zabbix-server
    image: zabbix-server-pgsql-custom:ol-5.2.7
  
    volumes:
      - ./files/server/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - ./files/server/odbc/odbc.ini:/etc/odbc.ini:ro
    environment: 
      - DB_SERVER_HOST=postgres
      - DB_SERVER_PORT=5432
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
      - ZBX_STARTDBSYNCERS=10
      - ZBX_CACHESIZE=64M
      - ZBX_CACHEUPDATEFREQUENCY=60
      - ZBX_HISTORYCACHESIZE=32M
      - ZBX_HISTORYINDEXCACHESIZE=64M
      - ZBX_TRENDCACHESIZE=64M
      - ZBX_VALUECACHESIZE=64M
      - TZ=America/Sao_Paulo
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 256M
    depends_on:
      - postgres
    ports:
      - 10051:10051
    networks:
      - net
      
  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ol-5.2.7
    environment: 
      - DB_SERVER_HOST=postgres
      - DB_SERVER_PORT=5432
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
      - PHP_TZ=America/Sao_Paulo
      - TZ=America/Sao_Paulo
    ports:
      - 80:8080
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 100M
    depends_on:
      - zabbix-server
      - postgres
    sysctls:
      - net.core.somaxconn=65535
    healthcheck:
      test: curl --fail --silent http://127.0.0.1:8080 2>&1 | grep SIA || exit 1
      interval: 60s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - net
      
  postgres:
    image: postgres:13-alpine
    volumes:
      - ./files/pgsql/data:/var/lib/postgresql/data:rw
    environment: 
      - DB_SERVER_HOST=postgres
      - DB_SERVER_PORT=5432
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix
      - POSTGRES_DB=zabbix
    networks:
      - net
